CREATE OR REPLACE DATABASE HMDA_DB;
CREATE OR REPLACE SCHEMA HMDA_DB.RAW;
CREATE OR REPLACE SCHEMA HMDA_DB.CLEAN;
CREATE OR REPLACE WAREHOUSE HMDA_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
USE WAREHOUSE HMDA_WH;
USE DATABASE HMDA_DB;
USE SCHEMA RAW;
/* I created a dedicated database (HMDA_DB), two schemas (RAW for landing data, CLEAN for transformed data)*/
